services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/volumes:/var/lib/mysql
    hostname: cats_db
    networks:
      - net_cats_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/app/.env
    container_name: api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_cats_db

networks:
  net_cats_db:
    driver: bridge
